name: jalvidyut
description: "Water & Electricity Tracking System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0 # Date Time Formater
  font_awesome_flutter: ^10.7.0 # Icons
  syncfusion_flutter_charts: ^26.2.14 # Graphs
  shared_preferences: ^2.3.0 # Save User Info

  firebase_core: ^3.3.0 # Firebase
  firebase_auth: ^5.1.3 # Firebase Authentication
  firebase_database: ^11.0.4 # Real Time Database
  cloud_firestore: ^5.2.0 # Firebase Firestore
  firebase_storage: ^12.1.2 # Storage

  get: ^4.6.6 # GetX
  image_picker: ^1.1.2 # Image Picker

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 # App Icon

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true


  assets:
    -  assets/images/

  fonts:
    - family: Roboto Regular
      fonts:
        - asset: assets/fonts/RobotoSerif-Regular.ttf

    - family: Roboto Bold
      fonts:
        - asset: assets/fonts/RobotoSerif-Bold.ttf