// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfSqs7DcJ5Pus1tsUlMNEVmodwOa-OTbM',
    appId: '1:343070882872:web:5ad98993ea09b7823c3acd',
    messagingSenderId: '343070882872',
    projectId: 'water-electricity-tracking',
    authDomain: 'water-electricity-tracking.firebaseapp.com',
    databaseURL: 'https://water-electricity-tracking-default-rtdb.firebaseio.com',
    storageBucket: 'water-electricity-tracking.appspot.com',
    measurementId: 'G-257X4F0WDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCdrWU3Jt8_rsVtkJfQBJUNLM0KoenKQg',
    appId: '1:343070882872:android:42619d6244689be63c3acd',
    messagingSenderId: '343070882872',
    projectId: 'water-electricity-tracking',
    databaseURL: 'https://water-electricity-tracking-default-rtdb.firebaseio.com',
    storageBucket: 'water-electricity-tracking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASusHlgG9PXEzgPET4J0spnzlW4BzaWB4',
    appId: '1:343070882872:ios:8954896cb9d33bfc3c3acd',
    messagingSenderId: '343070882872',
    projectId: 'water-electricity-tracking',
    databaseURL: 'https://water-electricity-tracking-default-rtdb.firebaseio.com',
    storageBucket: 'water-electricity-tracking.appspot.com',
    iosBundleId: 'com.jalvidyut.jalvidyut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfSqs7DcJ5Pus1tsUlMNEVmodwOa-OTbM',
    appId: '1:343070882872:web:b51739928671a4983c3acd',
    messagingSenderId: '343070882872',
    projectId: 'water-electricity-tracking',
    authDomain: 'water-electricity-tracking.firebaseapp.com',
    databaseURL: 'https://water-electricity-tracking-default-rtdb.firebaseio.com',
    storageBucket: 'water-electricity-tracking.appspot.com',
    measurementId: 'G-FM7LD2ZQQ0',
  );
}
